const compData = [
  {
    dias: new Date(2020, 5, 26, 0, 0),
    nomeCompeticao: "Campeonatos nacionais 2020",
    distrito: "Portalegre",
    regulamento: "Link para o regulamento",
    tipoProva: "Corrida",
  },
  {
    dias: new Date(2024, 2, 27, 0, 0),
    nomeCompeticao: "Torneio Rua de Rio Tinto",
    distrito: "Braga",
    regulamento: "Link para o regulamento",
    tipoProva: "Tipo A",
  },
  {
    dias: new Date(2024, 2, 23, 0, 0),
    nomeCompeticao: "I NOITE QUENTE",
    distrito: "Bragança",
    regulamento: "Link para o regulamento",
    tipoProva: "Tipo E",
  },
  {
    dias: new Date(2024, 4, 15, 0, 0),
    nomeCompeticao: "DIA DO MARTELO",
    distrito: "Faro",
    regulamento: "Link para o regulamento",
    tipoProva: "Tipo D",
  },
  {
    dias: new Date(2024, 4, 27, 0, 0),
    nomeCompeticao: "GOLD GALA FERNANDA RIBEIRO",
    distrito: "Castelo Branco",
    regulamento: "Link para o regulamento",
    tipoProva: "Tipo A",
  },
  {
    dias: new Date(2024, 3, 23, 0, 0),
    nomeCompeticao: "Campeonato de Provas Combinadas",
    distrito: "Guarda",
    regulamento: "Link para o regulamento",
    tipoProva: "Tipo F",
  },
  {
    dias: new Date(2024, 4, 30, 0, 0),
    nomeCompeticao: "Torneio de Marcha em Pista",
    distrito: "Leiria",
    regulamento: "Link para o regulamento",
    tipoProva: "Tipo C",
  },
  {
    dias: new Date(2024, 3, 7, 0, 0),
    nomeCompeticao: "XVIII MegaSprinter Nacional",
    distrito: "Beja",
    regulamento: "Link para o regulamento",
    tipoProva: "Tipo F",
  },
  {
    dias: new Date(2024, 3, 19, 0, 0),
    nomeCompeticao: "Campeonato Regional 10000 metros",
    distrito: "Viana do Castelo",
    regulamento: "Link para o regulamento",
    tipoProva: "Tipo F",
  },
  {
    dias: new Date(2024, 2, 20, 0, 0),
    nomeCompeticao: "MegaSprinter CLDE Porto",
    distrito: "Porto",
    regulamento: "Link para o regulamento",
    tipoProva: "Tipo C",
  },
  {
    dias: new Date(2024, 2, 5, 0, 0),
    nomeCompeticao: "TORNEIO DE PAVILHÃO",
    distrito: "Lisboa",
    regulamento: "Link para o regulamento",
    tipoProva: "Tipo D",
  },
  {
    dias: new Date(2024, 5, 17, 0, 0),
    nomeCompeticao: "Regional Corta Mato",
    distrito: "Lisboa",
    regulamento: "Link para o regulamento",
    tipoProva: "Tipo C",
  },
  {
    dias: new Date(2024, 5, 14, 0, 0),
    nomeCompeticao: "PROVAS PREPARAÇÃO",
    distrito: "Évora",
    regulamento: "Link para o regulamento",
    tipoProva: "Tipo B",
  },
  {
    dias: new Date(2024, 2, 15, 0, 0),
    nomeCompeticao: "CAMPEONATO DO NORTE DE MARCHA EM ESTRADA",
    distrito: "Guarda",
    regulamento: "Link para o regulamento",
    tipoProva: "Tipo E",
  },
  {
    dias: new Date(2024, 4, 27, 0, 0),
    nomeCompeticao: "Torneio de Pavilhão de Rio Tinto",
    distrito: "Lisboa",
    regulamento: "Link para o regulamento",
    tipoProva: "Tipo B",
  },
  {
    dias: new Date(2024, 5, 13, 0, 0),
    nomeCompeticao: "Prova de Lançamentos",
    distrito: "Viana do Castelo",
    regulamento: "Link para o regulamento",
    tipoProva: "Tipo G",
  },
  {
    dias: new Date(2024, 4, 27, 0, 0),
    nomeCompeticao: "TORNEIO DE ABERTURA JOVEM",
    distrito: "Viseu",
    regulamento: "Link para o regulamento",
    tipoProva: "Tipo D",
  },
  {
    dias: new Date(2024, 3, 15, 0, 0),
    nomeCompeticao: "MEETING ATLETISMO CUP",
    distrito: "Viana do Castelo",
    regulamento: "Link para o regulamento",
    tipoProva: "Tipo D",
  },
  {
    dias: new Date(2024, 5, 26, 0, 0),
    nomeCompeticao: "CORTA MATO DO CALÇADO JOVEM",
    distrito: "Viana do Castelo",
    regulamento: "Link para o regulamento",
    tipoProva: "Tipo B",
  },
  {
    dias: new Date(2024, 2, 23, 0, 0),
    nomeCompeticao: "CORTA MATO DE ABERTURA",
    distrito: "Setúbal",
    regulamento: "Link para o regulamento",
    tipoProva: "Tipo F",
  },
  {
    dias: new Date(2024, 5, 6, 0, 0),
    nomeCompeticao: "MEETING MATOSINHOS CUP",
    distrito: "Porto",
    regulamento: "Link para o regulamento",
    tipoProva: "Tipo A",
  },
  {
    dias: new Date(2024, 4, 13, 0, 0),
    nomeCompeticao: "campeonatos nacionais  21",
    distrito: "Castelo Branco",
    regulamento: "Link para o regulamento",
    tipoProva: "Tipo C",
  },
  {
    dias: new Date(2024, 3, 10, 0, 0),
    nomeCompeticao: "TORNEIO REGIONAL ESTAFETAS",
    distrito: "Lisboa",
    regulamento: "Link para o regulamento",
    tipoProva: "Tipo G",
  },
  {
    dias: new Date(2024, 2, 28, 0, 0),
    nomeCompeticao: "CAMPEONATO ABSOLUTO",
    distrito: "Évora",
    regulamento: "Link para o regulamento",
    tipoProva: "Tipo G",
  },
  {
    dias: new Date(2024, 3, 28, 0, 0),
    nomeCompeticao: "MEETING PEDRO GONÇALVES",
    distrito: "Coimbra",
    regulamento: "Link para o regulamento",
    tipoProva: "Tipo B",
  },
  {
    dias: new Date(2024, 3, 4, 0, 0),
    nomeCompeticao: "Meeting Maia Cidade do Desporto",
    distrito: "Coimbra",
    regulamento: "Link para o regulamento",
    tipoProva: "Tipo C",
  },
  {
    dias: new Date(2024, 3, 11, 0, 0),
    nomeCompeticao: "CAMPEONATO REGIONAL MASTERS",
    distrito: "Santarém",
    regulamento: "Link para o regulamento",
    tipoProva: "Tipo B",
  },
  {
    dias: new Date(2024, 3, 21, 0, 0),
    nomeCompeticao: "III NOITE QUENTE",
    distrito: "Braga",
    regulamento: "Link para o regulamento",
    tipoProva: "Tipo G",
  },
  {
    dias: new Date(2024, 2, 10, 0, 0),
    nomeCompeticao: "CAMPEONATO REGIONAL SUB18",
    distrito: "Coimbra",
    regulamento: "Link para o regulamento",
    tipoProva: "Tipo E",
  },
  {
    dias: new Date(2024, 2, 26, 0, 0),
    nomeCompeticao: "II NOITE QUENTE",
    distrito: "Guarda",
    regulamento: "Link para o regulamento",
    tipoProva: "Tipo C",
  },
];

export default compData;
